export const QUESTIONS = [
  { text: "Ta friandise sucrée préférée ?", options: ["Chocolat", "Bonbons", "Glace", "Pâtisserie"] },
  { text: "Ton moment de la journée préféré ?", options: ["Le matin", "L'après-midi", "Le soir", "La nuit"] },
  { text: "Ta façon idéale de passer un dimanche ?", options: ["Cocooning à la maison", "Sortie en plein air", "Voir des amis", "Sport ou activité"] },
  { text: "Ton style de vacances préféré ?", options: ["Plage", "Montagne", "Ville", "Road trip"] },
  { text: "Ce qui te stresse le plus ?", options: ["Le retard", "Le désordre", "L'imprévu", "Le silence gênant"] },
  { text: "Ton genre de film préféré ?", options: ["Comédie", "Action", "Romance", "Horreur"] },
  { text: "Ta boisson chaude préférée ?", options: ["Café", "Thé", "Chocolat chaud", "Aucune"] },
  { text: "Ton animal préféré ?", options: ["Chien", "Chat", "Oiseau", "Autre"] },
  { text: "Ta saison préférée ?", options: ["Printemps", "Été", "Automne", "Hiver"] },
  { text: "Ta façon de te détendre après une journée dure ?", options: ["Regarder une série", "Faire du sport", "Parler à quelqu'un", "Être seul·e"] },
  { text: "Ton plat préféré ?", options: ["Salé et copieux", "Sucré", "Épicé", "Léger et sain"] },
  { text: "Ton rêve de cadeau surprise ?", options: ["Voyage", "Bijou ou objet", "Soirée spéciale", "Rien, une lettre suffit"] },
  { text: "Ta plus grande peur (raisonnable) ?", options: ["Le vide", "Les insectes", "L'échec", "La solitude"] },
  { text: "Ton super-pouvoir de rêve ?", options: ["Voler", "Téléportation", "Lire les pensées", "Invisibilité"] },
  { text: "Comment tu préfères recevoir de l'amour ?", options: ["Mots doux", "Gestes/cadeaux", "Temps ensemble", "Câlins"] },
  { text: "Ton style musical préféré ?", options: ["Pop", "Rap/Hip-hop", "Rock", "Autre"] },
  { text: "Ta réaction face à un désaccord ?", options: ["J'en parle tout de suite", "J'ai besoin de temps", "Je cherche un compromis", "J'évite le sujet"] },
  { text: "Ton lieu de rendez-vous idéal ?", options: ["Restaurant", "Balade en plein air", "Soirée à la maison", "Activité originale"] },
  { text: "Ce que tu ferais avec un jour de libre imprévu ?", options: ["Dormir", "Sortir", "Cuisiner", "Un projet perso"] },
  { text: "Ton objet du quotidien que tu ne pourrais pas perdre ?", options: ["Téléphone", "Clés", "Portefeuille", "Écouteurs"] },
];
